import json
import os

def run_qemu_boot_audit():
    audit_results = {
        "patch_id": "STAGE-028",
        "verdict": "FAIL",
        "checks": []
    }

    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    report_path = os.path.join(project_root, "outputs/audits/qemu_boot_smoke_report.json")
    log_path = os.path.join(project_root, "outputs/audits/qemu_serial_capture.log")
    timing_path = os.path.join(project_root, "outputs/audits/qemu_boot_timing.json")

    # 1. Check Heartbeat Log Existence
    if os.path.exists(log_path):
        audit_results["checks"].append({"check": "Serial heartbeat log captured", "status": "PASS"})
    else:
        audit_results["checks"].append({"check": "Serial heartbeat log captured", "status": "FAIL"})

    # 2. Check Timing Data Existence
    if os.path.exists(timing_path):
        audit_results["checks"].append({"check": "Boot timing data captured", "status": "PASS"})
    else:
        audit_results["checks"].append({"check": "Boot timing data captured", "status": "FAIL"})

    # 3. Check Signal Verification (from report)
    # We load the report generated by the smoke runner
    if os.path.exists(report_path):
        with open(report_path, 'r') as f:
            report = json.load(f)
        
        if report.get("verdict") == "PASS":
             audit_results["checks"].append({"check": "All required boot signals detected", "status": "PASS"})
        else:
             audit_results["checks"].append({"check": "All required boot signals detected", "status": "FAIL", "reason": f"Missing: {report.get('missing_signals')}"})
    else:
        audit_results["checks"].append({"check": "Smoke test report generated", "status": "FAIL"})

    # Final verdict
    if all(check["status"] == "PASS" for check in audit_results["checks"]):
        audit_results["verdict"] = "PASS"
    else:
        audit_results["verdict"] = "FAIL"

    final_audit_path = os.path.join(project_root, "outputs/audits/qemu_boot_smoke_audit.json")
    with open(final_audit_path, 'w') as f:
        json.dump(audit_results, f, indent=2)

    print(f"Boot audit written to {final_audit_path}")
    return audit_results

if __name__ == "__main__":
    run_qemu_boot_audit()
